S6 box192 diegoardila
Diego-Ardila/SharedBox pull request #44
Opened 2020-09-28 00:06 UTC by Diego-Ardila

adding the pagination bar with the opyion to select the number of elements rendered on each page
![Captura de pantalla 2020-09-27 18 50 25](https://user-images.githubusercontent.com/67027844/94379210-85199a80-00f4-11eb-9ce6-56307c27022c.png)

2020-09-28 16:27 UTC, simonhoyos requested changes

2020-09-28 16:27 UTC, simonhoyos commented on src/utils/HTTPrequests.js
> +        throw err
Este throw puede romper el código. La idea del `catch` es capturar los errores para que la aplicación siga funcionando. Si lanzas un error desde el catch no va a haber quien capture el error

2020-09-28 23:55 UTC, Diego-Ardila commented on src/utils/HTTPrequests.js
> +        throw err
es que desde el lado en que se esta invocando ese axios hay un try{} catch{} que necesito que me reciba ese error; si le pongo simplemente return no me lo pasa al catch sino que me lo devuelve como el response.

2020-09-29 18:25 UTC, simonhoyos approved these changes

2020-09-30 16:31 UTC, merged