S0 box80 donaldo llanos diego m artinez
Diego-Ardila/SharedBox pull request #9
Opened 2020-08-18 22:18 UTC by ldonaldo

Final commit of the profile form.

2020-08-18 22:23 UTC, simonhoyos requested changes

2020-08-18 22:23 UTC, simonhoyos commented on src/components/profile/DisplayProfile.js
> +    setName(name=props.data.name);
Si los valores ya vienen por props simplemente puedes renderizar esos valores. No es necesario crear un nuevo estado para manejar valores que ya existen dentro de la aplicación

2020-08-18 22:23 UTC, simonhoyos commented on src/pages/profile.js
> +            },()=>{console.log(this.state.data)})
Remover los console.log y los console.dir

2020-08-18 22:23 UTC, simonhoyos commented on src/pages/profile.js
> +                {this.state.showProfile ? <DisplayProfile data={this.state.data}/> : <ProfileForm data={this.state.data} handleClick={this.handleClick}/>}
Estas 2 condiciones son iguales. Quizas podemos manejar un solo condicional

2020-08-18 22:40 UTC, ldonaldo commented on src/components/profile/DisplayProfile.js
> +    setName(name=props.data.name);
Con este destructuring es suficiente?
const {name,email,averageScore,phoneNumber,createdAt,country,city} = props.data;

2020-08-19 11:47 UTC, simonhoyos approved these changes

2020-08-19 13:24 UTC, merged